### ISSUE TITLE
runParallel error

### ISSUE THREAD

**Issue by ClockworkHou** [BhallaLab/FindSim#15]
I'm running FindSim on my Ubuntu18.04 machine.
When running runAllParallel.py file, error happens:

> ............multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/houchen/HouChen/GSoC_INCF/FindSim/findSim.py", line 1518, in innerMain
>     model.modify( modelId, erSPlist,modelWarning )
>   File "/home/houchen/HouChen/GSoC_INCF/FindSim/findSim.py", line 693, in modify
>     obj.setField( field, value )
> AttributeError: 'moose.BufPool' object has no attribute 'isBuffered'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "runAllParallel.py", line 124, in <module>
>     main()
>   File "runAllParallel.py", line 107, in main
>     results = [ i.get() for i in ret ]
>   File "runAllParallel.py", line 107, in <listcomp>
>     results = [ i.get() for i in ret ]
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
>     raise self._value
> AttributeError: 'moose.BufPool' object has no attribute 'isBuffered'

Do you know the reason or how to fix this?

My python version is 3.6.7.
And I used `pip install pymoose` to install moose.
(P.S. when building moose from repo, ctest#21 & #26 fails, I don't know weather this has something to do with errors when running FindSim.)

**Comment by surbhit21** [comment]
HI clockworkgenius,

The error may be because pymoose might be using an older version of moose. Can you try loading the model file in terminal using `moose.loadModel('modelfile','/test')`
after that
try:
`moose.showfields(moose.element('path_to_a_bufpool'))`
if there is no isBuffered attribute that it must be a pymoose error.

**Comment by ClockworkHou** [comment]
> 
> 
> HI clockworkgenius,
> 
> The error may be because pymoose might be using an older version of moose. Can you try loading the model file in terminal using `moose.loadModel('modelfile','/test')`
> after that
> try:
> `moose.showfields(moose.element('path_to_a_bufpool'))`
> if there is no isBuffered attribute that it must be a pymoose error.

I settled this problem just now by installing pymoose using `pip install pymoose --user --pre --upgrde`. Thank you!

**Comment by ClockworkHou** [comment]
I guess this can be closed.
