### ISSUE TITLE
moose version compatibility

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/FindSim#16]
When importing moose, FindSim should check if available version is compatible with it or not. Current devel branch is not compatible with current stable `3.1.4` release.

**Comment by hrani** [comment]
I think
pip install pymoose default should have a latest moose code rather that  ``
pip install pymoose --user --pre --upgrade`  people in the lab itself were
facing this problem.
Default people want to go with latest release
We can check the in FindSim also.


---------- Forwarded message ---------

**Comment by dilawar** [comment]
That would require official stable release. PyPI does not put nightly release
into stable channels.

See https://github.com/BhallaLab/moose/issues/238 .

best,
    Dilawar
--

**Comment by dilawar** [comment]
#19 Will install appropriate version of `moose` if merged to mainline.
